 id |            name            |                                                                                                                                                                     description                                                                                                                                                                      |      image       | price_cents | quantity |         created_at         |         updated_at         | category_id 
----+----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+-------------+----------+----------------------------+----------------------------+-------------
  1 | Men's Classy shirt         | Sustainable flexitarian celiac williamsburg blog. Before they sold out pickled pitchfork vinyl messenger bag leggings. Heirloom mlkshk neutra letterpress slow-carb whatever wolf. Franzen hella bushwick celiac vinyl pbr&b.                                                                                                                        | apparel1.jpg     |        6499 |       10 | 2017-08-02 20:38:35.137091 | 2017-08-02 20:38:35.137091 |           1
  2 | Women's Zebra pants        | Health williamsburg vhs brooklyn vinegar. Everyday try-hard meditation ennui forage whatever gentrify. Vinyl bicycle rights health twee typewriter biodiesel mustache etsy. Kogi chartreuse tumblr tacos. Pabst godard lomo. Tumblr small batch sartorial park artisan.                                                                              | apparel2.jpg     |       12499 |       18 | 2017-08-02 20:38:35.28449  | 2017-08-02 20:38:35.28449  |           1
  3 | Hipster Hat                | Ennui single-origin coffee chicharrones selvage slow-carb. Hella portland fanny pack pbr&b poutine. Migas knausgaard actually kogi. Messenger bag roof flannel you probably haven't heard of them forage jean shorts. Lomo selvage vinegar marfa 3 wolf moon everyday listicle hammock. Diy salvia normcore everyday cliche umami blue bottle tilde. | apparel3.jpg     |        3449 |        4 | 2017-08-02 20:38:35.462232 | 2017-08-02 20:38:35.462232 |           1
  4 | Hipster Socks              | Taxidermy next level vinegar wolf. Intelligentsia 3 wolf moon fashion axe selfies selvage. Irony chambray fixie celiac master park. Mixtape before they sold out wolf butcher intelligentsia health.                                                                                                                                                 | apparel4.jpg     |        2500 |        8 | 2017-08-02 20:38:35.79338  | 2017-08-02 20:38:35.79338  |           1
  5 | Russian Spy Shoes          | Brooklyn tacos chillwave cliche. Xoxo selvage kitsch everyday slow-carb bicycle rights. Small batch yr vhs kinfolk five dollar toast bushwick meditation fanny pack. Kale chips authentic chambray poutine portland raw denim thundercats typewriter. Fingerstache skateboard sustainable forage. Viral banh mi fanny pack gastropub.                | apparel5.jpg     |      122500 |        8 | 2017-08-02 20:38:35.967443 | 2017-08-02 20:38:35.967443 |           1
  6 | Human Feet Shoes           | Poutine health chia salvia. Pork belly typewriter paleo. Wes anderson chia flannel hella listicle vhs celiac pour-over. Jean shorts umami disrupt trust fund listicle.                                                                                                                                                                               | apparel6.jpg     |       22450 |       82 | 2017-08-02 20:38:36.151091 | 2017-08-02 20:38:36.151091 |           1
  7 | Modern Skateboards         | Typewriter meh cred before they sold out bushwick fingerstache meditation. Selfies drinking raw denim mustache master. Church-key kombucha pork belly. Art party aesthetic paleo vinyl tilde occupy vinegar. 3 wolf moon tacos lomo.                                                                                                                 | electronics1.jpg |       16449 |       40 | 2017-08-02 20:38:36.348788 | 2017-08-02 20:38:36.348788 |           2
  8 | Hotdog Slicer              | Farm-to-table neutra hammock +1 cornhole pbr&b master authentic. Goth intelligentsia godard. Beard pickled meditation humblebrag cliche craft beer migas diy. Readymade five dollar toast stumptown. Tilde godard street viral pop-up authentic blog farm-to-table. Quinoa art party goth kickstarter.                                               | electronics2.jpg |        2600 |        3 | 2017-08-02 20:38:36.525729 | 2017-08-02 20:38:36.525729 |           2
  9 | World's Largest Smartwatch | Microdosing vegan knausgaard salvia cardigan. 3 wolf moon paleo wayfarers celiac vhs everyday williamsburg. Wolf pork belly kitsch. Kinfolk seitan pickled fixie. Sustainable banjo put a bird on it bitters. Pitchfork +1 viral.                                                                                                                    | electronics3.jpg |      202629 |       32 | 2017-08-02 20:38:36.698726 | 2017-08-02 20:38:36.698726 |           2
 10 | Optimal Sleeping Bed       | Marfa biodiesel bushwick shabby chic semiotics selvage godard. Master lomo swag keffiyeh taxidermy viral disrupt bushwick. Kombucha echo try-hard kinfolk xoxo. Gluten-free selvage polaroid pug ethical hoodie yr everyday. Sriracha blue bottle forage distillery single-origin coffee raw denim narwhal mustache.                                 | furniture1.jpg   |      305200 |      320 | 2017-08-02 20:38:36.866396 | 2017-08-02 20:38:36.866396 |           3
 11 | Electric Chair             | Freegan yolo poutine meditation godard tofu. Chambray squid authentic semiotics. Twee forage austin keytar seitan meh readymade literally. Cray helvetica forage. Vhs wolf hashtag retro crucifix before they sold out.                                                                                                                              | furniture2.jpg   |       98765 |        2 | 2017-08-02 20:38:37.053045 | 2017-08-02 20:38:37.053045 |           3
 12 | Red Bookshelf              | Bicycle rights pickled semiotics. Fingerstache iphone fanny pack post-ironic authentic gluten-free fap. Dreamcatcher cray actually lumbersexual 90's yolo. Artisan synth vegan organic wayfarers asymmetrical. Try-hard bicycle rights master chambray locavore.                                                                                     | furniture3.jpg   |      248375 |        0 | 2017-08-02 20:38:37.35356  | 2017-08-02 20:38:37.35356  |           3
(12 rows)

